/*
 ** File: UserPrivilegesValidator.java
 **
 ** Date Created: December 2013
 **
 ** Copyright @ 2004-2013 Smart Business Technology, Inc.
 **
 ** All rights reserved. No part of this software may be 
 ** reproduced, transmitted, transcribed, stored in a retrieval 
 ** system, or translated into any language or computer language, 
 ** in any form or by any means, electronic, mechanical, magnetic, 
 ** optical, chemical, manual or otherwise, without the prior 
 ** written permission of Smart Business Technology, Inc.
 **
 */
package com.smartbt.vtsuite.vtcommon.nomenclators;

/**
 *
 * UserPrivilegesValidator class
 */
public enum NomUserPrivileges {

    
      ALLOW_BOARDING(1),
      ALLOW_BOARDING_MANAGEMENT(12),
      ALLOW_BOARDING_MANAGEMENT_REMOVE(17),
      ALLOW_BOARDING_MANAGEMENT_AGRUPATION(13),
      ALLOW_BOARDING_MANAGEMENT_AGRUPATION_ADD(18),
      ALLOW_BOARDING_MANAGEMENT_AGRUPATION_ADD_MERCHANT(21),
      ALLOW_BOARDING_MANAGEMENT_MERCHANT_ADD(19),
      ALLOW_BOARDING_MANAGEMENT_MERCHANT_ADD_TERMINAL(22),
      ALLOW_BOARDING_MANAGEMENT_MERCHANT(14),
      ALLOW_BOARDING_MANAGEMENT_TERMINAL(15),
      ALLOW_BOARDING_MANAGEMENT_TERMINAL_ADD(20),
      ALLOW_BOARDING_APLICATION(16),
      ALLOW_TRANSACTION(2),
      ALLOW_ADDRESS(3),
      ALLOW_ADMINISTRATION(4),
      
      ALLOW_ADMINISTRATION_USERS(6),
      ALLOW_ADMINISTRATION_USERS_UPDATE(9),
      ALLOW_ADMINISTRATION_ROLES(5),
      ALLOW_ADMINISTRATION_ROLES_ADD_PRIVILEGE(7),
      ALLOW_ADMINISTRATION_ROLES_NEW(11),
      ALLOW_ADMINISTRATION_ROLES_DELETE(8),
      ALLOW_ADMINISTRATION_ROLES_DELETE_PRIVILEGE(10),
      ALLOW_ADMINISTRATION_USERS_CHANGE_PASSWORD(23)
//    ALLOW_MERCHANT_SERVICES(1),
//    ALLOW_MERCHANT_TRANSACTIONS(2),
//    //ALLOW_MERCHANT_USERS(3),
//    ALLOW_MERCHANT_CUSTOMER(4),
//    ALLOW_MERCHANT_CUSTOMER_IMPORT(5),
//    ALLOW_MERCHANT_CUSTOMER_ADD(6),
//    ALLOW_MERCHANT_CUSTOMER_UPDATE(7),
//    ALLOW_MERCHANT_CUSTOMER_DELETE(8),
//    ALLOW_MERCHANT_CUSTOMER_DELETE_ALL(9),
//    ALLOW_MERCHANT_RECURRING(10),
//    ALLOW_MERCHANT_RECURRING_IMPORT(11),
//    ALLOW_MERCHANT_RECURRING_ADD(12),
//    ALLOW_MERCHANT_RECURRING_UPDATE(13),
//    ALLOW_MERCHANT_RECURRING_DELETE(14),
//    ALLOW_MERCHANT_RECURRING_DELETE_ALL(15),
//    ALLOW_MERCHANT_SETTINGS_PARAMETERS(16),
//    ALLOW_MERCHANT_SETTINGS_PARAMETERS_ADD(17),
//    ALLOW_MERCHANT_SETTINGS_PARAMETERS_UPDATE(18),
//    ALLOW_MERCHANT_SETTINGS_USERS(19),
//    ALLOW_BOARDING_ROLES(20),
//    ALLOW_BOARDING_ROLES_NEW(21),
//    ALLOW_BOARDING_ROLES_ADD_PRIVILEGE(22),
//    ALLOW_BOARDING_ROLES_DELETE_PRIVILEGE(23),
//    
//    
//    ALLOW_WATCHDOG(24),    
//    ALLOW_WATCHDOG_RULES_ADD(25),
//    ALLOW_WATCHDOG_RULES_UPDATE(26),
//    ALLOW_WATCHDOG_RULES_DELETE(27),
//    
//    
//    ALLOW_BOARDING(28),
//    ALLOW_BOARDING_STATUS(29),
//    ALLOW_BOARDING_APP_PARAM(30),
//    ALLOW_BOARDING_APP_PARAM_APP_MANAGEMENT_NEW_APP(31),
//    ALLOW_BOARDING_APP_PARAM_APP_MANAGEMENT_ADD(32),
//    ALLOW_BOARDING_APP_PARAM_APP_MANAGEMENT_UPDATE(33),
//    ALLOW_MONITORING(34),
//    ALLOW_MONITORING_ACTIVATION(35),
//    ALLOW_MONITORING_DEACTIVATION(36),
//    ALLOW_AUDIT(37),
//    ALLOW_AUDIT_MERCHANT(38),
//    ALLOW_AUDIT_AMS(39),
//    ALLOW_SERVER(40),
//    
//    
//    
//    ALLOW_WATCHDOG_RULES(41),//ALLOW_SERVER_WATCHDOG(41),
//    ALLOW_WATCHDOG_ALERT_DELETE(42),
//    ALLOW_WATCHDOG_ALERT_DELETE_ALL(43),
//    
//    
//    
//    ALLOW_SETTINGS(44),
//    ALLOW_SETTINGS_PARAMETERS(45),
//    ALLOW_SETTINGS_USERS(46),
//    ALLOW_SETTINGS_ROLES(47),
//    ALLOW_SETTINGS_PARAMETERS_ADD(48),
//    ALLOW_SETTINGS_PARAMETERS_UPDATE(49),
//    ALLOW_SETTINGS_USERS_UPDATE(50),
//    ALLOW_SETTINGS_ROLES_NEW(51),
//    ALLOW_SETTINGS_ROLES_ADD_PRIVILEGE(52),
//    ALLOW_SETTINGS_ROLES_DELETE_PRIVILEGE(53),
//    ALLOW_DASHBOARD(54),
//    ALLOW_MERCHANT_SETTINGS(55),
//    ALLOW_MERCHANT_SETTINGS_USERS_UPDATE(56),
//    ALLOW_MERCHANT_SETTINGS_PARAMETERS_DELETE(57),
//    ALLOW_BOARDING_APP_PARAM_APP_MANAGEMENT(58),
//    ALLOW_BOARDING_APP_PARAM_APP_MANAGEMENT_DELETE(59),
//    ALLOW_BOARDING_APP_PARAM_GLOBAL_LISTING(60),
//    ALLOW_BOARDING_APP_PARAM_GLOBAL_LISTING_ADD_PARAMETER(61),
//    ALLOW_BOARDING_APP_PARAM_GLOBAL_LISTING_UPDATE_PARAMETER(62),
//    ALLOW_BOARDING_APP_PARAM_GLOBAL_LISTING_DELETE_PARAMETER(63),
//    
//    
//   
//    ALLOW_WATCHDOG_ALERT(64),  
    
//    
//    ALLOW_MERCHANT_WATCHDOG_ALERT_DELETE(66),
//    ALLOW_MERCHANT_WATCHDOG_ALERT_DELETE_ALL(67),
//    
//    ALLOW_SERVER_WATCHDOG_RULES(68),
//    ALLOW_SERVER_WATCHDOG_ALERT(69),    
//    ALLOW_SERVER_WATCHDOG_RULES_ADD(70),
//    ALLOW_SERVER_WATCHDOG_RULES_UPDATE(71),
//    ALLOW_SERVER_WATCHDOG_RULES_DELETE(72)
    ;
    
    
    
    private int id;

    private NomUserPrivileges(int id) {
        this.id = id;
    }

    /**
     * Get id
     *
     * @return the id
     */
    public int getId() {
        return id;
    }
   
}
