//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.08 at 02:12:15 PM EDT 
//
package com.smartbt.girocheck.scan;

import com.smartbt.girocheck.servercommon.enums.ParameterName;
import com.smartbt.girocheck.servercommon.enums.TransactionType;
import com.smartbt.girocheck.servercommon.utils.IBuilder;
import com.smartbt.girocheck.servercommon.utils.IMap;
import com.smartbt.vtsuite.util.MapUtil;
import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;


@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "", propOrder = {
    "transacciono"
} )
@XmlRootElement( name = "LOTE_SALIDA" )
public class LOTESALIDA implements IBuilder {
    private String authoNumber;
    private String opCode;
    private String opCode2;
    private String idConsignor;
    private String idBeneficiary;
    private String bankAutho;
    

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString( this );
    }

    @Override
    public LOTESALIDA build(Map map) throws Exception {
        authoNumber = MapUtil.getStringValueFromMap(map, ParameterName.AUTHO_NUMBER, false);
        opCode = MapUtil.getStringValueFromMap(map, ParameterName.OP_CODE, false);
        opCode2 = MapUtil.getStringValueFromMap(map, ParameterName.OP_CODE2, false);
        idConsignor = MapUtil.getStringValueFromMap(map, ParameterName.IDCONSIGNOR, false);
        idBeneficiary = MapUtil.getStringValueFromMap(map, ParameterName.ID_BENEFICIARY, false);
        bankAutho = MapUtil.getStringValueFromMap(map, ParameterName.BANK_AUTHO, false);
        
        return this;
    }

    /**
     * @return the authoNumber
     */
    public String getAuthoNumber() {
        return authoNumber;
    }

    /**
     * @param authoNumber the authoNumber to set
     */
    public void setAuthoNumber(String authoNumber) {
        this.authoNumber = authoNumber;
    }

    /**
     * @return the opCode
     */
    public String getOpCode() {
        return opCode;
    }

    /**
     * @param opCode the opCode to set
     */
    public void setOpCode(String opCode) {
        this.opCode = opCode;
    }

    /**
     * @return the opCode2
     */
    public String getOpCode2() {
        return opCode2;
    }

    /**
     * @param opCode2 the opCode2 to set
     */
    public void setOpCode2(String opCode2) {
        this.opCode2 = opCode2;
    }

    /**
     * @return the idConsignor
     */
    public String getIdConsignor() {
        return idConsignor;
    }

    /**
     * @param idConsignor the idConsignor to set
     */
    public void setIdConsignor(String idConsignor) {
        this.idConsignor = idConsignor;
    }

    /**
     * @return the idBeneficiary
     */
    public String getIdBeneficiary() {
        return idBeneficiary;
    }

    /**
     * @param idBeneficiary the idBeneficiary to set
     */
    public void setIdBeneficiary(String idBeneficiary) {
        this.idBeneficiary = idBeneficiary;
    }

    /**
     * @return the bankAutho
     */
    public String getBankAutho() {
        return bankAutho;
    }

    /**
     * @param bankAutho the bankAutho to set
     */
    public void setBankAutho(String bankAutho) {
        this.bankAutho = bankAutho;
    }

    
    
}
