
package com.smartbt.girocheck.scan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Scan", targetNamespace = "http://scan.girocheck.smartbt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Scan {


    
       /**
     * 
     * @param arg0
     * @return
     *     returns com.smartbt.girocheck.scan.PersonalInfoRes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderExpress", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.OrderExpress")
    @ResponseWrapper(localName = "orderExpressResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.OrderExpressResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/orderExpressRequest", output = "http://scan.girocheck.smartbt.com/Scan/orderExpressResponse")
    public OrderExpressRes orderExpress(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderExpressRequest arg0);
    
     @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAuth", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuth")
    @ResponseWrapper(localName = "checkAuthResponse", targetNamespace = "http://scan.girocheck.smartbt.com/", className = "com.smartbt.girocheck.scan.CheckAuthResponse")
    @Action(input = "http://scan.girocheck.smartbt.com/Scan/checkAuthRequest", output = "http://scan.girocheck.smartbt.com/Scan/checkAuthResponse")
    public CheckAuthRes checkAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        CheckAuthRequest arg0);
    
}
