update state set statecode = 'FL' where name = 'FLORIDA';
update state set statecode = 'TX' where name = 'TEXAS';
update state set statecode = 'WA' where name = 'WASHINGTON';
update state set statecode = 'CA' where name = 'LOS ANGELES';
update state set statecode = 'GA' where name = 'GEORGIA';
update state set statecode = 'NY' where name = 'NEW YORK';
update state set statecode = 'AL' where name = 'ALABAMA';
update state set statecode = 'HI' where name = 'HAWAII';
update state set statecode = 'VA' where name = 'VIRGINIA';
update state set statecode = 'AZ' where name = 'ARIZONA';
update state set statecode = 'OR' where name = 'OREGON';
update state set statecode = 'VT' where name = 'VERMONT';
update state set statecode = 'KS' where name = 'KANSAS';
update state set statecode = 'CA' where name = 'CALIFORNIA';
update state set statecode = 'CO' where name = 'COLORADO';
update state set statecode = 'AK' where name = 'ALASKA'; 
update state set statecode = 'AL' where name = 'ALABAMA';
update state set statecode = 'ID' where name = 'IDAHO';
update state set statecode = 'DE' where name = 'DELAWARE';
update state set statecode = 'NV' where name = 'NEVADA';
update state set statecode = 'MT' where name = 'MONTANA';
update state set statecode = 'IN' where name = 'INDIANA';
update state set statecode = 'NE' where name = 'NEBRASKA';
update state set statecode = 'ME' where name = 'MAINE';
update state set statecode = 'AR' where name = 'ARKANSAS';
update state set statecode = 'CT' where name = 'CONNECTICUT';
update state set statecode = 'DC' where name = 'DISTRICT OF COLUMBIA';
update state set statecode = 'IL' where name = 'ILLINOIS';
update state set statecode = 'IA' where name = 'IOWA';
update state set statecode = 'KY' where name = 'KENTUCKY';
update state set statecode = 'LA' where name = 'LOUISIANA';
update state set statecode = 'MD' where name = 'MARYLAND';
update state set statecode = 'MA' where name = 'MASSACHUSETTS';
update state set statecode = 'MI' where name = 'MICHIGAN';
update state set statecode = 'MN' where name = 'MINESOTA';
update state set statecode = 'MS' where name = 'MISSISSIPI';
update state set statecode = 'NH' where name = 'NEW HAMPSHIRE';
update state set statecode = 'NJ' where name = 'NEW JERSEY';
update state set statecode = 'NM' where name = 'NEW MEXICO'; 
update state set statecode = 'NC' where name = 'NORTH CAROLINA';
update state set statecode = 'ND' where name = 'NORTH DAKOTA';
update state set statecode = 'OH' where name = 'OHIO';
update state set statecode = 'OK' where name = 'OKLAHOMA';
update state set statecode = 'PA' where name = 'PENNSYLVANIA';
update state set statecode = 'RI' where name = 'RHODE ISLAND';
update state set statecode = 'SC' where name = 'SOUTH CAROLINA';
update state set statecode = 'SD' where name = 'SOUTH DAKOTA';
update state set statecode = 'TN' where name = 'TENNESEE';
update state set statecode = 'UT' where name = 'UTAH';
update state set statecode = 'WV' where name = 'WEST VIRGINIA';
update state set statecode = 'WI' where name = 'WISCONSIN';
update state set statecode = 'WY' where name = 'WYOMING';
update state set statecode = 'MO' where name = 'MISSOURI';
update state set statecode = 'KS' where name = 'KANSAS';